int bitAnd(int, int);
int test_bitAnd(int, int);
int fitsShort(int);
int test_fitsShort(int);
int anyEvenBit();
int test_anyEvenBit();
int isLess(int, int);
int test_isLess(int, int);
int greatestBitPos(int);
int test_greatestBitPos(int);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
